# first query
query{
    organization(login:"ScalaConsultants") {
        membersWithRole(first:100) {
            pageInfo{
                hasNextPage
                startCursor
                endCursor
            }
            totalCount
            nodes{
                login
                contributionsCollection {
                    contributionCalendar {
                        totalContributions
                    }
                }
            }
        }
    }
}