package com.github

package object graph {
  type Base64String = String

  type Date = String

  type DateTime = String

  type GitObjectID = String

  type GitRefname = String

  type GitSSHRemote = String

  type GitTimestamp = String

  type HTML = String

  type PreciseDateTime = String

  type URI = String

  type X509Certificate = String

  type AcceptEnterpriseAdministratorInvitationPayload
  type AcceptTopicSuggestionPayload
  type ActorLocation
  type AddAssigneesToAssignablePayload
  type AddCommentPayload
  type AddDiscussionCommentPayload
  type AddEnterpriseSupportEntitlementPayload
  type AddLabelsToLabelablePayload
  type AddProjectCardPayload
  type AddProjectColumnPayload
  type AddProjectNextItemPayload
  type AddPullRequestReviewCommentPayload
  type AddPullRequestReviewPayload
  type AddPullRequestReviewThreadPayload
  type AddReactionPayload
  type AddStarPayload
  type AddUpvotePayload
  type AddVerifiableDomainPayload
  type AddedToProjectEvent
  type App
  type ApproveDeploymentsPayload
  type ApproveVerifiableDomainPayload
  type ArchiveRepositoryPayload
  type AssignedEvent
  type AutoMergeDisabledEvent
  type AutoMergeEnabledEvent
  type AutoMergeRequest
  type AutoRebaseEnabledEvent
  type AutoSquashEnabledEvent
  type AutomaticBaseChangeFailedEvent
  type AutomaticBaseChangeSucceededEvent
  type BaseRefChangedEvent
  type BaseRefDeletedEvent
  type BaseRefForcePushedEvent
  type Blame
  type BlameRange
  type Blob
  type Bot
  type BranchProtectionRule
  type BranchProtectionRuleConflict
  type BranchProtectionRuleConflictConnection
  type BranchProtectionRuleConflictEdge
  type BranchProtectionRuleConnection
  type BranchProtectionRuleEdge
  type CVSS
  type CWE
  type CWEConnection
  type CWEEdge
  type CancelEnterpriseAdminInvitationPayload
  type CancelSponsorshipPayload
  type ChangeUserStatusPayload
  type CheckAnnotation
  type CheckAnnotationConnection
  type CheckAnnotationEdge
  type CheckAnnotationPosition
  type CheckAnnotationSpan
  type CheckRun
  type CheckRunConnection
  type CheckRunEdge
  type CheckStep
  type CheckStepConnection
  type CheckStepEdge
  type CheckSuite
  type CheckSuiteConnection
  type CheckSuiteEdge
  type ClearLabelsFromLabelablePayload
  type CloneProjectPayload
  type CloneTemplateRepositoryPayload
  type CloseIssuePayload
  type ClosePullRequestPayload
  type ClosedEvent
  type CodeOfConduct
  type CommentDeletedEvent
  type Commit
  type CommitComment
  type CommitCommentConnection
  type CommitCommentEdge
  type CommitCommentThread
  type CommitConnection
  type CommitContributionsByRepository
  type CommitEdge
  type CommitHistoryConnection
  type ConnectedEvent
  type ContentAttachment
  type ContentReference
  type ContributionCalendar
  type ContributionCalendarDay
  type ContributionCalendarMonth
  type ContributionCalendarWeek
  type ContributionsCollection
  type ConvertProjectCardNoteToIssuePayload
  type ConvertPullRequestToDraftPayload
  type ConvertToDraftEvent
  type ConvertedNoteToIssueEvent
  type CreateBranchProtectionRulePayload
  type CreateCheckRunPayload
  type CreateCheckSuitePayload
  type CreateCommitOnBranchPayload
  type CreateContentAttachmentPayload
  type CreateDeploymentPayload
  type CreateDeploymentStatusPayload
  type CreateDiscussionPayload
  type CreateEnterpriseOrganizationPayload
  type CreateEnvironmentPayload
  type CreateIpAllowListEntryPayload
  type CreateIssuePayload
  type CreateLabelPayload
  type CreateProjectPayload
  type CreatePullRequestPayload
  type CreateRefPayload
  type CreateRepositoryPayload
  type CreateSponsorshipPayload
  type CreateTeamDiscussionCommentPayload
  type CreateTeamDiscussionPayload
  type CreatedCommitContribution
  type CreatedCommitContributionConnection
  type CreatedCommitContributionEdge
  type CreatedIssueContribution
  type CreatedIssueContributionConnection
  type CreatedIssueContributionEdge
  type CreatedPullRequestContribution
  type CreatedPullRequestContributionConnection
  type CreatedPullRequestContributionEdge
  type CreatedPullRequestReviewContribution
  type CreatedPullRequestReviewContributionConnection
  type CreatedPullRequestReviewContributionEdge
  type CreatedRepositoryContribution
  type CreatedRepositoryContributionConnection
  type CreatedRepositoryContributionEdge
  type CrossReferencedEvent
  type DeclineTopicSuggestionPayload
  type DeleteBranchProtectionRulePayload
  type DeleteDeploymentPayload
  type DeleteDiscussionCommentPayload
  type DeleteDiscussionPayload
  type DeleteEnvironmentPayload
  type DeleteIpAllowListEntryPayload
  type DeleteIssueCommentPayload
  type DeleteIssuePayload
  type DeleteLabelPayload
  type DeletePackageVersionPayload
  type DeleteProjectCardPayload
  type DeleteProjectColumnPayload
  type DeleteProjectNextItemPayload
  type DeleteProjectPayload
  type DeletePullRequestReviewCommentPayload
  type DeletePullRequestReviewPayload
  type DeleteRefPayload
  type DeleteTeamDiscussionCommentPayload
  type DeleteTeamDiscussionPayload
  type DeleteVerifiableDomainPayload
  type DemilestonedEvent
  type DependencyGraphDependency
  type DependencyGraphDependencyConnection
  type DependencyGraphDependencyEdge
  type DependencyGraphManifest
  type DependencyGraphManifestConnection
  type DependencyGraphManifestEdge
  type DeployKey
  type DeployKeyConnection
  type DeployKeyEdge
  type DeployedEvent
  type Deployment
  type DeploymentConnection
  type DeploymentEdge
  type DeploymentEnvironmentChangedEvent
  type DeploymentProtectionRule
  type DeploymentProtectionRuleConnection
  type DeploymentProtectionRuleEdge
  type DeploymentRequest
  type DeploymentRequestConnection
  type DeploymentRequestEdge
  type DeploymentReview
  type DeploymentReviewConnection
  type DeploymentReviewEdge
  type DeploymentReviewerConnection
  type DeploymentReviewerEdge
  type DeploymentStatus
  type DeploymentStatusConnection
  type DeploymentStatusEdge
  type DisablePullRequestAutoMergePayload
  type DisconnectedEvent
  type Discussion
  type DiscussionCategory
  type DiscussionCategoryConnection
  type DiscussionCategoryEdge
  type DiscussionComment
  type DiscussionCommentConnection
  type DiscussionCommentEdge
  type DiscussionConnection
  type DiscussionEdge
  type DismissPullRequestReviewPayload
  type DismissRepositoryVulnerabilityAlertPayload
  type EnablePullRequestAutoMergePayload
  type Enterprise
  type EnterpriseAdministratorConnection
  type EnterpriseAdministratorEdge
  type EnterpriseAdministratorInvitation
  type EnterpriseAdministratorInvitationConnection
  type EnterpriseAdministratorInvitationEdge
  type EnterpriseBillingInfo
  type EnterpriseIdentityProvider
  type EnterpriseMemberConnection
  type EnterpriseMemberEdge
  type EnterpriseOrganizationMembershipConnection
  type EnterpriseOrganizationMembershipEdge
  type EnterpriseOutsideCollaboratorConnection
  type EnterpriseOutsideCollaboratorEdge
  type EnterpriseOwnerInfo
  type EnterprisePendingCollaboratorConnection
  type EnterprisePendingCollaboratorEdge
  type EnterprisePendingMemberInvitationConnection
  type EnterprisePendingMemberInvitationEdge
  type EnterpriseRepositoryInfo
  type EnterpriseRepositoryInfoConnection
  type EnterpriseRepositoryInfoEdge
  type EnterpriseServerInstallation
  type EnterpriseServerInstallationConnection
  type EnterpriseServerInstallationEdge
  type EnterpriseServerUserAccount
  type EnterpriseServerUserAccountConnection
  type EnterpriseServerUserAccountEdge
  type EnterpriseServerUserAccountEmail
  type EnterpriseServerUserAccountEmailConnection
  type EnterpriseServerUserAccountEmailEdge
  type EnterpriseServerUserAccountsUpload
  type EnterpriseServerUserAccountsUploadConnection
  type EnterpriseServerUserAccountsUploadEdge
  type EnterpriseUserAccount
  type EnterpriseUserAccountConnection
  type EnterpriseUserAccountEdge
  type Environment
  type EnvironmentConnection
  type EnvironmentEdge
  type ExternalIdentity
  type ExternalIdentityConnection
  type ExternalIdentityEdge
  type ExternalIdentitySamlAttributes
  type ExternalIdentityScimAttributes
  type FollowUserPayload
  type FollowerConnection
  type FollowingConnection
  type FundingLink
  type GenericHovercardContext
  type Gist
  type GistComment
  type GistCommentConnection
  type GistCommentEdge
  type GistConnection
  type GistEdge
  type GistFile
  type GitActor
  type GitActorConnection
  type GitActorEdge
  type GitHubMetadata
  type GpgSignature
  type HeadRefDeletedEvent
  type HeadRefForcePushedEvent
  type HeadRefRestoredEvent
  type Hovercard
  type ImportProjectPayload
  type InviteEnterpriseAdminPayload
  type IpAllowListEntry
  type IpAllowListEntryConnection
  type IpAllowListEntryEdge
  type Issue
  type IssueComment
  type IssueCommentConnection
  type IssueCommentEdge
  type IssueConnection
  type IssueContributionsByRepository
  type IssueEdge
  type IssueTemplate
  type IssueTimelineConnection
  type IssueTimelineItemEdge
  type IssueTimelineItemsConnection
  type IssueTimelineItemsEdge
  type JoinedGitHubContribution
  type Label
  type LabelConnection
  type LabelEdge
  type LabeledEvent
  type Language
  type LanguageConnection
  type LanguageEdge
  type License
  type LicenseRule
  type LinkRepositoryToProjectPayload
  type LockLockablePayload
  type LockedEvent
  type Mannequin
  type MarkDiscussionCommentAsAnswerPayload
  type MarkFileAsViewedPayload
  type MarkPullRequestReadyForReviewPayload
  type MarkedAsDuplicateEvent
  type MarketplaceCategory
  type MarketplaceListing
  type MarketplaceListingConnection
  type MarketplaceListingEdge
  type MembersCanDeleteReposClearAuditEntry
  type MembersCanDeleteReposDisableAuditEntry
  type MembersCanDeleteReposEnableAuditEntry
  type MentionedEvent
  type MergeBranchPayload
  type MergePullRequestPayload
  type MergedEvent
  type Milestone
  type MilestoneConnection
  type MilestoneEdge
  type MilestonedEvent
  type MinimizeCommentPayload
  type MoveProjectCardPayload
  type MoveProjectColumnPayload
  type MovedColumnsInProjectEvent
  type OIDCProvider
  type OauthApplicationCreateAuditEntry
  type OrgAddBillingManagerAuditEntry
  type OrgAddMemberAuditEntry
  type OrgBlockUserAuditEntry
  type OrgConfigDisableCollaboratorsOnlyAuditEntry
  type OrgConfigEnableCollaboratorsOnlyAuditEntry
  type OrgCreateAuditEntry
  type OrgDisableOauthAppRestrictionsAuditEntry
  type OrgDisableSamlAuditEntry
  type OrgDisableTwoFactorRequirementAuditEntry
  type OrgEnableOauthAppRestrictionsAuditEntry
  type OrgEnableSamlAuditEntry
  type OrgEnableTwoFactorRequirementAuditEntry
  type OrgInviteMemberAuditEntry
  type OrgInviteToBusinessAuditEntry
  type OrgOauthAppAccessApprovedAuditEntry
  type OrgOauthAppAccessDeniedAuditEntry
  type OrgOauthAppAccessRequestedAuditEntry
  type OrgRemoveBillingManagerAuditEntry
  type OrgRemoveMemberAuditEntry
  type OrgRemoveOutsideCollaboratorAuditEntry
  type OrgRestoreMemberAuditEntry
  type OrgRestoreMemberMembershipOrganizationAuditEntryData
  type OrgRestoreMemberMembershipRepositoryAuditEntryData
  type OrgRestoreMemberMembershipTeamAuditEntryData
  type OrgUnblockUserAuditEntry
  type OrgUpdateDefaultRepositoryPermissionAuditEntry
  type OrgUpdateMemberAuditEntry
  type OrgUpdateMemberRepositoryCreationPermissionAuditEntry
  type OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
  type Organization
  type OrganizationAuditEntryConnection
  type OrganizationAuditEntryEdge
  type OrganizationConnection
  type OrganizationEdge
  type OrganizationIdentityProvider
  type OrganizationInvitation
  type OrganizationInvitationConnection
  type OrganizationInvitationEdge
  type OrganizationMemberConnection
  type OrganizationMemberEdge
  type OrganizationTeamsHovercardContext
  type OrganizationsHovercardContext
  type Package_1
  type PackageConnection
  type PackageEdge
  type PackageFile
  type PackageFileConnection
  type PackageFileEdge
  type PackageStatistics
  type PackageTag
  type PackageVersion
  type PackageVersionConnection
  type PackageVersionEdge
  type PackageVersionStatistics
  type PageInfo
  type PermissionSource
  type PinIssuePayload
  type PinnableItemConnection
  type PinnableItemEdge
  type PinnedDiscussion
  type PinnedDiscussionConnection
  type PinnedDiscussionEdge
  type PinnedEvent
  type PinnedIssue
  type PinnedIssueConnection
  type PinnedIssueEdge
  type PrivateRepositoryForkingDisableAuditEntry
  type PrivateRepositoryForkingEnableAuditEntry
  type ProfileItemShowcase
  type Project
  type ProjectCard
  type ProjectCardConnection
  type ProjectCardEdge
  type ProjectColumn
  type ProjectColumnConnection
  type ProjectColumnEdge
  type ProjectConnection
  type ProjectEdge
  type ProjectNext
  type ProjectNextConnection
  type ProjectNextEdge
  type ProjectNextField
  type ProjectNextFieldConnection
  type ProjectNextFieldEdge
  type ProjectNextItem
  type ProjectNextItemConnection
  type ProjectNextItemEdge
  type ProjectNextItemFieldValue
  type ProjectNextItemFieldValueConnection
  type ProjectNextItemFieldValueEdge
  type ProjectProgress
  type PublicKey
  type PublicKeyConnection
  type PublicKeyEdge
  type PullRequest
  type PullRequestChangedFile
  type PullRequestChangedFileConnection
  type PullRequestChangedFileEdge
  type PullRequestCommit
  type PullRequestCommitCommentThread
  type PullRequestCommitConnection
  type PullRequestCommitEdge
  type PullRequestConnection
  type PullRequestContributionsByRepository
  type PullRequestEdge
  type PullRequestReview
  type PullRequestReviewComment
  type PullRequestReviewCommentConnection
  type PullRequestReviewCommentEdge
  type PullRequestReviewConnection
  type PullRequestReviewContributionsByRepository
  type PullRequestReviewEdge
  type PullRequestReviewThread
  type PullRequestReviewThreadConnection
  type PullRequestReviewThreadEdge
  type PullRequestRevisionMarker
  type PullRequestTemplate
  type PullRequestTimelineConnection
  type PullRequestTimelineItemEdge
  type PullRequestTimelineItemsConnection
  type PullRequestTimelineItemsEdge
  type Push
  type PushAllowance
  type PushAllowanceConnection
  type PushAllowanceEdge
  type RateLimit
  type ReactingUserConnection
  type ReactingUserEdge
  type Reaction
  type ReactionConnection
  type ReactionEdge
  type ReactionGroup
  type ReactorConnection
  type ReactorEdge
  type ReadyForReviewEvent
  type Ref
  type RefConnection
  type RefEdge
  type RefUpdateRule
  type ReferencedEvent
  type RegenerateEnterpriseIdentityProviderRecoveryCodesPayload
  type RegenerateVerifiableDomainTokenPayload
  type RejectDeploymentsPayload
  type Release
  type ReleaseAsset
  type ReleaseAssetConnection
  type ReleaseAssetEdge
  type ReleaseConnection
  type ReleaseEdge
  type RemoveAssigneesFromAssignablePayload
  type RemoveEnterpriseAdminPayload
  type RemoveEnterpriseIdentityProviderPayload
  type RemoveEnterpriseOrganizationPayload
  type RemoveEnterpriseSupportEntitlementPayload
  type RemoveLabelsFromLabelablePayload
  type RemoveOutsideCollaboratorPayload
  type RemoveReactionPayload
  type RemoveStarPayload
  type RemoveUpvotePayload
  type RemovedFromProjectEvent
  type RenamedTitleEvent
  type ReopenIssuePayload
  type ReopenPullRequestPayload
  type ReopenedEvent
  type RepoAccessAuditEntry
  type RepoAddMemberAuditEntry
  type RepoAddTopicAuditEntry
  type RepoArchivedAuditEntry
  type RepoChangeMergeSettingAuditEntry
  type RepoConfigDisableAnonymousGitAccessAuditEntry
  type RepoConfigDisableCollaboratorsOnlyAuditEntry
  type RepoConfigDisableContributorsOnlyAuditEntry
  type RepoConfigDisableSockpuppetDisallowedAuditEntry
  type RepoConfigEnableAnonymousGitAccessAuditEntry
  type RepoConfigEnableCollaboratorsOnlyAuditEntry
  type RepoConfigEnableContributorsOnlyAuditEntry
  type RepoConfigEnableSockpuppetDisallowedAuditEntry
  type RepoConfigLockAnonymousGitAccessAuditEntry
  type RepoConfigUnlockAnonymousGitAccessAuditEntry
  type RepoCreateAuditEntry
  type RepoDestroyAuditEntry
  type RepoRemoveMemberAuditEntry
  type RepoRemoveTopicAuditEntry
  type Repository
  type RepositoryCollaboratorConnection
  type RepositoryCollaboratorEdge
  type RepositoryConnection
  type RepositoryContactLink
  type RepositoryEdge
  type RepositoryInteractionAbility
  type RepositoryInvitation
  type RepositoryInvitationConnection
  type RepositoryInvitationEdge
  type RepositoryTopic
  type RepositoryTopicConnection
  type RepositoryTopicEdge
  type RepositoryVisibilityChangeDisableAuditEntry
  type RepositoryVisibilityChangeEnableAuditEntry
  type RepositoryVulnerabilityAlert
  type RepositoryVulnerabilityAlertConnection
  type RepositoryVulnerabilityAlertEdge
  type RequestReviewsPayload
  type RequiredStatusCheckDescription
  type RerequestCheckSuitePayload
  type ResolveReviewThreadPayload
  type RestrictedContribution
  type ReviewDismissalAllowance
  type ReviewDismissalAllowanceConnection
  type ReviewDismissalAllowanceEdge
  type ReviewDismissedEvent
  type ReviewRequest
  type ReviewRequestConnection
  type ReviewRequestEdge
  type ReviewRequestRemovedEvent
  type ReviewRequestedEvent
  type ReviewStatusHovercardContext
  type SavedReply
  type SavedReplyConnection
  type SavedReplyEdge
  type SearchResultItemConnection
  type SearchResultItemEdge
  type SecurityAdvisory
  type SecurityAdvisoryConnection
  type SecurityAdvisoryEdge
  type SecurityAdvisoryIdentifier
  type SecurityAdvisoryPackage
  type SecurityAdvisoryPackageVersion
  type SecurityAdvisoryReference
  type SecurityVulnerability
  type SecurityVulnerabilityConnection
  type SecurityVulnerabilityEdge
  type SetEnterpriseIdentityProviderPayload
  type SetOrganizationInteractionLimitPayload
  type SetRepositoryInteractionLimitPayload
  type SetUserInteractionLimitPayload
  type SmimeSignature
  type SponsorConnection
  type SponsorEdge
  type SponsorableItemConnection
  type SponsorableItemEdge
  type SponsorsActivity
  type SponsorsActivityConnection
  type SponsorsActivityEdge
  type SponsorsGoal
  type SponsorsListing
  type SponsorsTier
  type SponsorsTierAdminInfo
  type SponsorsTierConnection
  type SponsorsTierEdge
  type Sponsorship
  type SponsorshipConnection
  type SponsorshipEdge
  type SponsorshipNewsletter
  type SponsorshipNewsletterConnection
  type SponsorshipNewsletterEdge
  type StargazerConnection
  type StargazerEdge
  type StarredRepositoryConnection
  type StarredRepositoryEdge
  type Status
  type StatusCheckRollup
  type StatusCheckRollupContextConnection
  type StatusCheckRollupContextEdge
  type StatusContext
  type SubmitPullRequestReviewPayload
  type Submodule
  type SubmoduleConnection
  type SubmoduleEdge
  type SubscribedEvent
  type SuggestedReviewer
  type Tag
  type Team
  type TeamAddMemberAuditEntry
  type TeamAddRepositoryAuditEntry
  type TeamChangeParentTeamAuditEntry
  type TeamConnection
  type TeamDiscussion
  type TeamDiscussionComment
  type TeamDiscussionCommentConnection
  type TeamDiscussionCommentEdge
  type TeamDiscussionConnection
  type TeamDiscussionEdge
  type TeamEdge
  type TeamMemberConnection
  type TeamMemberEdge
  type TeamRemoveMemberAuditEntry
  type TeamRemoveRepositoryAuditEntry
  type TeamRepositoryConnection
  type TeamRepositoryEdge
  type TextMatch
  type TextMatchHighlight
  type Topic
  type TransferIssuePayload
  type TransferredEvent
  type Tree
  type TreeEntry
  type UnarchiveRepositoryPayload
  type UnassignedEvent
  type UnfollowUserPayload
  type UnknownSignature
  type UnlabeledEvent
  type UnlinkRepositoryFromProjectPayload
  type UnlockLockablePayload
  type UnlockedEvent
  type UnmarkDiscussionCommentAsAnswerPayload
  type UnmarkFileAsViewedPayload
  type UnmarkIssueAsDuplicatePayload
  type UnmarkedAsDuplicateEvent
  type UnminimizeCommentPayload
  type UnpinIssuePayload
  type UnpinnedEvent
  type UnresolveReviewThreadPayload
  type UnsubscribedEvent
  type UpdateBranchProtectionRulePayload
  type UpdateCheckRunPayload
  type UpdateCheckSuitePreferencesPayload
  type UpdateDiscussionCommentPayload
  type UpdateDiscussionPayload
  type UpdateEnterpriseAdministratorRolePayload
  type UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload
  type UpdateEnterpriseDefaultRepositoryPermissionSettingPayload
  type UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload
  type UpdateEnterpriseMembersCanCreateRepositoriesSettingPayload
  type UpdateEnterpriseMembersCanDeleteIssuesSettingPayload
  type UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload
  type UpdateEnterpriseMembersCanInviteCollaboratorsSettingPayload
  type UpdateEnterpriseMembersCanMakePurchasesSettingPayload
  type UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload
  type UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload
  type UpdateEnterpriseOrganizationProjectsSettingPayload
  type UpdateEnterpriseProfilePayload
  type UpdateEnterpriseRepositoryProjectsSettingPayload
  type UpdateEnterpriseTeamDiscussionsSettingPayload
  type UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload
  type UpdateEnvironmentPayload
  type UpdateIpAllowListEnabledSettingPayload
  type UpdateIpAllowListEntryPayload
  type UpdateIpAllowListForInstalledAppsEnabledSettingPayload
  type UpdateIssueCommentPayload
  type UpdateIssuePayload
  type UpdateLabelPayload
  type UpdateNotificationRestrictionSettingPayload
  type UpdateProjectCardPayload
  type UpdateProjectColumnPayload
  type UpdateProjectNextItemFieldPayload
  type UpdateProjectPayload
  type UpdatePullRequestBranchPayload
  type UpdatePullRequestPayload
  type UpdatePullRequestReviewCommentPayload
  type UpdatePullRequestReviewPayload
  type UpdateRefPayload
  type UpdateRefsPayload
  type UpdateRepositoryPayload
  type UpdateSponsorshipPreferencesPayload
  type UpdateSubscriptionPayload
  type UpdateTeamDiscussionCommentPayload
  type UpdateTeamDiscussionPayload
  type UpdateTeamReviewAssignmentPayload
  type UpdateTopicsPayload
  type User
  type UserBlockedEvent
  type UserConnection
  type UserContentEdit
  type UserContentEditConnection
  type UserContentEditEdge
  type UserEdge
  type UserEmailMetadata
  type UserStatus
  type UserStatusConnection
  type UserStatusEdge
  type VerifiableDomain
  type VerifiableDomainConnection
  type VerifiableDomainEdge
  type VerifyVerifiableDomainPayload
  type ViewerHovercardContext
  type Workflow
  type WorkflowRun
  type Query    = _root_.caliban.client.Operations.RootQuery
  type Mutation = _root_.caliban.client.Operations.RootMutation
}

