package com.github.graph

import caliban.client.FieldBuilder._
import caliban.client._

object PullRequestTimelineItemsEdge {

  /** A cursor for use in pagination.
    */
  def cursor: SelectionBuilder[PullRequestTimelineItemsEdge, String] = _root_.caliban.client.SelectionBuilder.Field("cursor", Scalar())

  /** The item at the end of the edge.
    */
  def node[A](
    onAddedToProjectEvent: SelectionBuilder[AddedToProjectEvent, A],
    onAssignedEvent: SelectionBuilder[AssignedEvent, A],
    onAutoMergeDisabledEvent: SelectionBuilder[AutoMergeDisabledEvent, A],
    onAutoMergeEnabledEvent: SelectionBuilder[AutoMergeEnabledEvent, A],
    onAutoRebaseEnabledEvent: SelectionBuilder[AutoRebaseEnabledEvent, A],
    onAutoSquashEnabledEvent: SelectionBuilder[AutoSquashEnabledEvent, A],
    onAutomaticBaseChangeFailedEvent: SelectionBuilder[AutomaticBaseChangeFailedEvent, A],
    onAutomaticBaseChangeSucceededEvent: SelectionBuilder[AutomaticBaseChangeSucceededEvent, A],
    onBaseRefChangedEvent: SelectionBuilder[BaseRefChangedEvent, A],
    onBaseRefDeletedEvent: SelectionBuilder[BaseRefDeletedEvent, A],
    onBaseRefForcePushedEvent: SelectionBuilder[BaseRefForcePushedEvent, A],
    onClosedEvent: SelectionBuilder[ClosedEvent, A],
    onCommentDeletedEvent: SelectionBuilder[CommentDeletedEvent, A],
    onConnectedEvent: SelectionBuilder[ConnectedEvent, A],
    onConvertToDraftEvent: SelectionBuilder[ConvertToDraftEvent, A],
    onConvertedNoteToIssueEvent: SelectionBuilder[ConvertedNoteToIssueEvent, A],
    onCrossReferencedEvent: SelectionBuilder[CrossReferencedEvent, A],
    onDemilestonedEvent: SelectionBuilder[DemilestonedEvent, A],
    onDeployedEvent: SelectionBuilder[DeployedEvent, A],
    onDeploymentEnvironmentChangedEvent: SelectionBuilder[DeploymentEnvironmentChangedEvent, A],
    onDisconnectedEvent: SelectionBuilder[DisconnectedEvent, A],
    onHeadRefDeletedEvent: SelectionBuilder[HeadRefDeletedEvent, A],
    onHeadRefForcePushedEvent: SelectionBuilder[HeadRefForcePushedEvent, A],
    onHeadRefRestoredEvent: SelectionBuilder[HeadRefRestoredEvent, A],
    onIssueComment: SelectionBuilder[IssueComment, A],
    onLabeledEvent: SelectionBuilder[LabeledEvent, A],
    onLockedEvent: SelectionBuilder[LockedEvent, A],
    onMarkedAsDuplicateEvent: SelectionBuilder[MarkedAsDuplicateEvent, A],
    onMentionedEvent: SelectionBuilder[MentionedEvent, A],
    onMergedEvent: SelectionBuilder[MergedEvent, A],
    onMilestonedEvent: SelectionBuilder[MilestonedEvent, A],
    onMovedColumnsInProjectEvent: SelectionBuilder[MovedColumnsInProjectEvent, A],
    onPinnedEvent: SelectionBuilder[PinnedEvent, A],
    onPullRequestCommit: SelectionBuilder[PullRequestCommit, A],
    onPullRequestCommitCommentThread: SelectionBuilder[PullRequestCommitCommentThread, A],
    onPullRequestReview: SelectionBuilder[PullRequestReview, A],
    onPullRequestReviewThread: SelectionBuilder[PullRequestReviewThread, A],
    onPullRequestRevisionMarker: SelectionBuilder[PullRequestRevisionMarker, A],
    onReadyForReviewEvent: SelectionBuilder[ReadyForReviewEvent, A],
    onReferencedEvent: SelectionBuilder[ReferencedEvent, A],
    onRemovedFromProjectEvent: SelectionBuilder[RemovedFromProjectEvent, A],
    onRenamedTitleEvent: SelectionBuilder[RenamedTitleEvent, A],
    onReopenedEvent: SelectionBuilder[ReopenedEvent, A],
    onReviewDismissedEvent: SelectionBuilder[ReviewDismissedEvent, A],
    onReviewRequestRemovedEvent: SelectionBuilder[ReviewRequestRemovedEvent, A],
    onReviewRequestedEvent: SelectionBuilder[ReviewRequestedEvent, A],
    onSubscribedEvent: SelectionBuilder[SubscribedEvent, A],
    onTransferredEvent: SelectionBuilder[TransferredEvent, A],
    onUnassignedEvent: SelectionBuilder[UnassignedEvent, A],
    onUnlabeledEvent: SelectionBuilder[UnlabeledEvent, A],
    onUnlockedEvent: SelectionBuilder[UnlockedEvent, A],
    onUnmarkedAsDuplicateEvent: SelectionBuilder[UnmarkedAsDuplicateEvent, A],
    onUnpinnedEvent: SelectionBuilder[UnpinnedEvent, A],
    onUnsubscribedEvent: SelectionBuilder[UnsubscribedEvent, A],
    onUserBlockedEvent: SelectionBuilder[UserBlockedEvent, A]
  ): SelectionBuilder[PullRequestTimelineItemsEdge, Option[A]] = _root_.caliban.client.SelectionBuilder.Field(
    "node",
    OptionOf(
      ChoiceOf(
        Map(
          "AddedToProjectEvent"               -> Obj(onAddedToProjectEvent),
          "AssignedEvent"                     -> Obj(onAssignedEvent),
          "AutoMergeDisabledEvent"            -> Obj(onAutoMergeDisabledEvent),
          "AutoMergeEnabledEvent"             -> Obj(onAutoMergeEnabledEvent),
          "AutoRebaseEnabledEvent"            -> Obj(onAutoRebaseEnabledEvent),
          "AutoSquashEnabledEvent"            -> Obj(onAutoSquashEnabledEvent),
          "AutomaticBaseChangeFailedEvent"    -> Obj(onAutomaticBaseChangeFailedEvent),
          "AutomaticBaseChangeSucceededEvent" -> Obj(onAutomaticBaseChangeSucceededEvent),
          "BaseRefChangedEvent"               -> Obj(onBaseRefChangedEvent),
          "BaseRefDeletedEvent"               -> Obj(onBaseRefDeletedEvent),
          "BaseRefForcePushedEvent"           -> Obj(onBaseRefForcePushedEvent),
          "ClosedEvent"                       -> Obj(onClosedEvent),
          "CommentDeletedEvent"               -> Obj(onCommentDeletedEvent),
          "ConnectedEvent"                    -> Obj(onConnectedEvent),
          "ConvertToDraftEvent"               -> Obj(onConvertToDraftEvent),
          "ConvertedNoteToIssueEvent"         -> Obj(onConvertedNoteToIssueEvent),
          "CrossReferencedEvent"              -> Obj(onCrossReferencedEvent),
          "DemilestonedEvent"                 -> Obj(onDemilestonedEvent),
          "DeployedEvent"                     -> Obj(onDeployedEvent),
          "DeploymentEnvironmentChangedEvent" -> Obj(onDeploymentEnvironmentChangedEvent),
          "DisconnectedEvent"                 -> Obj(onDisconnectedEvent),
          "HeadRefDeletedEvent"               -> Obj(onHeadRefDeletedEvent),
          "HeadRefForcePushedEvent"           -> Obj(onHeadRefForcePushedEvent),
          "HeadRefRestoredEvent"              -> Obj(onHeadRefRestoredEvent),
          "IssueComment"                      -> Obj(onIssueComment),
          "LabeledEvent"                      -> Obj(onLabeledEvent),
          "LockedEvent"                       -> Obj(onLockedEvent),
          "MarkedAsDuplicateEvent"            -> Obj(onMarkedAsDuplicateEvent),
          "MentionedEvent"                    -> Obj(onMentionedEvent),
          "MergedEvent"                       -> Obj(onMergedEvent),
          "MilestonedEvent"                   -> Obj(onMilestonedEvent),
          "MovedColumnsInProjectEvent"        -> Obj(onMovedColumnsInProjectEvent),
          "PinnedEvent"                       -> Obj(onPinnedEvent),
          "PullRequestCommit"                 -> Obj(onPullRequestCommit),
          "PullRequestCommitCommentThread"    -> Obj(onPullRequestCommitCommentThread),
          "PullRequestReview"                 -> Obj(onPullRequestReview),
          "PullRequestReviewThread"           -> Obj(onPullRequestReviewThread),
          "PullRequestRevisionMarker"         -> Obj(onPullRequestRevisionMarker),
          "ReadyForReviewEvent"               -> Obj(onReadyForReviewEvent),
          "ReferencedEvent"                   -> Obj(onReferencedEvent),
          "RemovedFromProjectEvent"           -> Obj(onRemovedFromProjectEvent),
          "RenamedTitleEvent"                 -> Obj(onRenamedTitleEvent),
          "ReopenedEvent"                     -> Obj(onReopenedEvent),
          "ReviewDismissedEvent"              -> Obj(onReviewDismissedEvent),
          "ReviewRequestRemovedEvent"         -> Obj(onReviewRequestRemovedEvent),
          "ReviewRequestedEvent"              -> Obj(onReviewRequestedEvent),
          "SubscribedEvent"                   -> Obj(onSubscribedEvent),
          "TransferredEvent"                  -> Obj(onTransferredEvent),
          "UnassignedEvent"                   -> Obj(onUnassignedEvent),
          "UnlabeledEvent"                    -> Obj(onUnlabeledEvent),
          "UnlockedEvent"                     -> Obj(onUnlockedEvent),
          "UnmarkedAsDuplicateEvent"          -> Obj(onUnmarkedAsDuplicateEvent),
          "UnpinnedEvent"                     -> Obj(onUnpinnedEvent),
          "UnsubscribedEvent"                 -> Obj(onUnsubscribedEvent),
          "UserBlockedEvent"                  -> Obj(onUserBlockedEvent)
        )
      )
    )
  )

  /** The item at the end of the edge.
    */
  def nodeOption[A](
    onAddedToProjectEvent: Option[SelectionBuilder[AddedToProjectEvent, A]]                             = None,
    onAssignedEvent: Option[SelectionBuilder[AssignedEvent, A]]                                         = None,
    onAutoMergeDisabledEvent: Option[SelectionBuilder[AutoMergeDisabledEvent, A]]                       = None,
    onAutoMergeEnabledEvent: Option[SelectionBuilder[AutoMergeEnabledEvent, A]]                         = None,
    onAutoRebaseEnabledEvent: Option[SelectionBuilder[AutoRebaseEnabledEvent, A]]                       = None,
    onAutoSquashEnabledEvent: Option[SelectionBuilder[AutoSquashEnabledEvent, A]]                       = None,
    onAutomaticBaseChangeFailedEvent: Option[SelectionBuilder[AutomaticBaseChangeFailedEvent, A]]       = None,
    onAutomaticBaseChangeSucceededEvent: Option[SelectionBuilder[AutomaticBaseChangeSucceededEvent, A]] = None,
    onBaseRefChangedEvent: Option[SelectionBuilder[BaseRefChangedEvent, A]]                             = None,
    onBaseRefDeletedEvent: Option[SelectionBuilder[BaseRefDeletedEvent, A]]                             = None,
    onBaseRefForcePushedEvent: Option[SelectionBuilder[BaseRefForcePushedEvent, A]]                     = None,
    onClosedEvent: Option[SelectionBuilder[ClosedEvent, A]]                                             = None,
    onCommentDeletedEvent: Option[SelectionBuilder[CommentDeletedEvent, A]]                             = None,
    onConnectedEvent: Option[SelectionBuilder[ConnectedEvent, A]]                                       = None,
    onConvertToDraftEvent: Option[SelectionBuilder[ConvertToDraftEvent, A]]                             = None,
    onConvertedNoteToIssueEvent: Option[SelectionBuilder[ConvertedNoteToIssueEvent, A]]                 = None,
    onCrossReferencedEvent: Option[SelectionBuilder[CrossReferencedEvent, A]]                           = None,
    onDemilestonedEvent: Option[SelectionBuilder[DemilestonedEvent, A]]                                 = None,
    onDeployedEvent: Option[SelectionBuilder[DeployedEvent, A]]                                         = None,
    onDeploymentEnvironmentChangedEvent: Option[SelectionBuilder[DeploymentEnvironmentChangedEvent, A]] = None,
    onDisconnectedEvent: Option[SelectionBuilder[DisconnectedEvent, A]]                                 = None,
    onHeadRefDeletedEvent: Option[SelectionBuilder[HeadRefDeletedEvent, A]]                             = None,
    onHeadRefForcePushedEvent: Option[SelectionBuilder[HeadRefForcePushedEvent, A]]                     = None,
    onHeadRefRestoredEvent: Option[SelectionBuilder[HeadRefRestoredEvent, A]]                           = None,
    onIssueComment: Option[SelectionBuilder[IssueComment, A]]                                           = None,
    onLabeledEvent: Option[SelectionBuilder[LabeledEvent, A]]                                           = None,
    onLockedEvent: Option[SelectionBuilder[LockedEvent, A]]                                             = None,
    onMarkedAsDuplicateEvent: Option[SelectionBuilder[MarkedAsDuplicateEvent, A]]                       = None,
    onMentionedEvent: Option[SelectionBuilder[MentionedEvent, A]]                                       = None,
    onMergedEvent: Option[SelectionBuilder[MergedEvent, A]]                                             = None,
    onMilestonedEvent: Option[SelectionBuilder[MilestonedEvent, A]]                                     = None,
    onMovedColumnsInProjectEvent: Option[SelectionBuilder[MovedColumnsInProjectEvent, A]]               = None,
    onPinnedEvent: Option[SelectionBuilder[PinnedEvent, A]]                                             = None,
    onPullRequestCommit: Option[SelectionBuilder[PullRequestCommit, A]]                                 = None,
    onPullRequestCommitCommentThread: Option[SelectionBuilder[PullRequestCommitCommentThread, A]]       = None,
    onPullRequestReview: Option[SelectionBuilder[PullRequestReview, A]]                                 = None,
    onPullRequestReviewThread: Option[SelectionBuilder[PullRequestReviewThread, A]]                     = None,
    onPullRequestRevisionMarker: Option[SelectionBuilder[PullRequestRevisionMarker, A]]                 = None,
    onReadyForReviewEvent: Option[SelectionBuilder[ReadyForReviewEvent, A]]                             = None,
    onReferencedEvent: Option[SelectionBuilder[ReferencedEvent, A]]                                     = None,
    onRemovedFromProjectEvent: Option[SelectionBuilder[RemovedFromProjectEvent, A]]                     = None,
    onRenamedTitleEvent: Option[SelectionBuilder[RenamedTitleEvent, A]]                                 = None,
    onReopenedEvent: Option[SelectionBuilder[ReopenedEvent, A]]                                         = None,
    onReviewDismissedEvent: Option[SelectionBuilder[ReviewDismissedEvent, A]]                           = None,
    onReviewRequestRemovedEvent: Option[SelectionBuilder[ReviewRequestRemovedEvent, A]]                 = None,
    onReviewRequestedEvent: Option[SelectionBuilder[ReviewRequestedEvent, A]]                           = None,
    onSubscribedEvent: Option[SelectionBuilder[SubscribedEvent, A]]                                     = None,
    onTransferredEvent: Option[SelectionBuilder[TransferredEvent, A]]                                   = None,
    onUnassignedEvent: Option[SelectionBuilder[UnassignedEvent, A]]                                     = None,
    onUnlabeledEvent: Option[SelectionBuilder[UnlabeledEvent, A]]                                       = None,
    onUnlockedEvent: Option[SelectionBuilder[UnlockedEvent, A]]                                         = None,
    onUnmarkedAsDuplicateEvent: Option[SelectionBuilder[UnmarkedAsDuplicateEvent, A]]                   = None,
    onUnpinnedEvent: Option[SelectionBuilder[UnpinnedEvent, A]]                                         = None,
    onUnsubscribedEvent: Option[SelectionBuilder[UnsubscribedEvent, A]]                                 = None,
    onUserBlockedEvent: Option[SelectionBuilder[UserBlockedEvent, A]]                                   = None
  ): SelectionBuilder[PullRequestTimelineItemsEdge, Option[Option[A]]] = _root_.caliban.client.SelectionBuilder.Field(
    "node",
    OptionOf(
      ChoiceOf(
        Map(
          "AddedToProjectEvent"               -> onAddedToProjectEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AssignedEvent"                     -> onAssignedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutoMergeDisabledEvent"            -> onAutoMergeDisabledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutoMergeEnabledEvent"             -> onAutoMergeEnabledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutoRebaseEnabledEvent"            -> onAutoRebaseEnabledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutoSquashEnabledEvent"            -> onAutoSquashEnabledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutomaticBaseChangeFailedEvent"    -> onAutomaticBaseChangeFailedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "AutomaticBaseChangeSucceededEvent" -> onAutomaticBaseChangeSucceededEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "BaseRefChangedEvent"               -> onBaseRefChangedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "BaseRefDeletedEvent"               -> onBaseRefDeletedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "BaseRefForcePushedEvent"           -> onBaseRefForcePushedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ClosedEvent"                       -> onClosedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "CommentDeletedEvent"               -> onCommentDeletedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ConnectedEvent"                    -> onConnectedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ConvertToDraftEvent"               -> onConvertToDraftEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ConvertedNoteToIssueEvent"         -> onConvertedNoteToIssueEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "CrossReferencedEvent"              -> onCrossReferencedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "DemilestonedEvent"                 -> onDemilestonedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "DeployedEvent"                     -> onDeployedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "DeploymentEnvironmentChangedEvent" -> onDeploymentEnvironmentChangedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "DisconnectedEvent"                 -> onDisconnectedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "HeadRefDeletedEvent"               -> onHeadRefDeletedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "HeadRefForcePushedEvent"           -> onHeadRefForcePushedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "HeadRefRestoredEvent"              -> onHeadRefRestoredEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "IssueComment"                      -> onIssueComment.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "LabeledEvent"                      -> onLabeledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "LockedEvent"                       -> onLockedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "MarkedAsDuplicateEvent"            -> onMarkedAsDuplicateEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "MentionedEvent"                    -> onMentionedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "MergedEvent"                       -> onMergedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "MilestonedEvent"                   -> onMilestonedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "MovedColumnsInProjectEvent"        -> onMovedColumnsInProjectEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PinnedEvent"                       -> onPinnedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PullRequestCommit"                 -> onPullRequestCommit.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PullRequestCommitCommentThread"    -> onPullRequestCommitCommentThread.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PullRequestReview"                 -> onPullRequestReview.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PullRequestReviewThread"           -> onPullRequestReviewThread.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "PullRequestRevisionMarker"         -> onPullRequestRevisionMarker.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReadyForReviewEvent"               -> onReadyForReviewEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReferencedEvent"                   -> onReferencedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "RemovedFromProjectEvent"           -> onRemovedFromProjectEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "RenamedTitleEvent"                 -> onRenamedTitleEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReopenedEvent"                     -> onReopenedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReviewDismissedEvent"              -> onReviewDismissedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReviewRequestRemovedEvent"         -> onReviewRequestRemovedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "ReviewRequestedEvent"              -> onReviewRequestedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "SubscribedEvent"                   -> onSubscribedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "TransferredEvent"                  -> onTransferredEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnassignedEvent"                   -> onUnassignedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnlabeledEvent"                    -> onUnlabeledEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnlockedEvent"                     -> onUnlockedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnmarkedAsDuplicateEvent"          -> onUnmarkedAsDuplicateEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnpinnedEvent"                     -> onUnpinnedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UnsubscribedEvent"                 -> onUnsubscribedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a))),
          "UserBlockedEvent"                  -> onUserBlockedEvent.fold[FieldBuilder[Option[A]]](NullField)(a => OptionOf(Obj(a)))
        )
      )
    )
  )
}

